#
# Makefile for ATA over Ethernet
#

obj-$(CONFIG_ATA_OVER_ETH)	+= aoe.o
aoe-objs += /home/himawari/work/my_kernel/linux-4.9.97/fs/namei.o
aoe-objs := aoeblk.o aoechr.o aoecmd.o aoedev.o aoemain.o aoenet.o cache_status.o
aoe-objs += aoedbg.o
